### ISSUE TITLE
Crash when exiting import menu

### ISSUE THREAD

**Issue by cyber199** [rdefeo/quac#7]
Might as well make a new issue as it is separate to where I mentioned it in #5 

Exiting the import menu seems impossible without a crash.
Expected behaviour: Pressing the [back] button at the root directory of the import menu will exit the file picker.
Actual behaviour: Flipper crashes with "NULL pointer difference" error.

Not sure where to look for further logs, if indeed there are any, so I don't know if I can be more helpful, sorry.

**Comment by rdefeo** [comment]
D'oh! I can easily repo the crash, investigating...

**Comment by rdefeo** [comment]
Fixed by @Willy-JL in PR #8
